Vagrant.configure("2") do |config|
  config.vm.box = "cloudicio/ubuntu-desktop"
  config.vm.box_version = "24.04.1"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.hostname = "vm-ubuntu-sandbox"

  #if ENV['DOTFILES_DIR']
  if true
    # config.vm.synced_folder ENV['DOTFILES_DIR'], "/home/sandbox/.dotfiles",
    config.vm.synced_folder "/Users/jcravo/.dotfiles", "/home/sandbox/.dotfiles",
      type: "rsync",
      rsync__auto: true,
      rsync__exclude: [".git/", "node_modules/", "*.swp"]
  else
    warn "DOTFILES_DIR environment variable not set. Skipping dotfiles sync."
  end

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.name = "Dotfiles playground - Ubuntu Desktop VM"
    v.cpus = 4
    v.memory = 8192
    v.customize ["setextradata", :id, "CustomVideoMode1", "1280x800x32"]

    # Prevent VirtualBox from launching in fullscreen
    v.customize ["setextradata", :id, "GUI/LastGuestSizeHint", "800,600"]
    v.customize ["setextradata", :id, "GUI/Fullscreen", "off"]
    v.customize ["setextradata", :id, "GUI/Seamless", "off"]
    v.customize ["setextradata", :id, "GUI/ScaleFactor", "1"]

    v.customize ["modifyvm", :id, "--vram", "256"]
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    # Avoid interactive prompts
    export DEBIAN_FRONTEND=noninteractive

    # Install required packages
    sudo apt-get update
    sudo apt-get install -y curl sudo ca-certificates build-essential dkms linux-headers-$(uname -r)

    # Create sandbox user if it doesn't exist
    if ! id sandbox >/dev/null 2>&1; then
      sudo useradd -m -s /bin/bash -G sudo sandbox
      sudo usermod --password $(openssl passwd -6 'sandbox') sandbox
      echo 'sandbox ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/sandbox
    fi

    mkdir -p /nix /home/sandbox
    sudo chown -R sandbox:sandbox /home/sandbox

    chmod +x /home/sandbox/.dotfiles/setup/bootstrap/ubuntu-bootstrap.sh
    /home/sandbox/.dotfiles/setup/bootstrap/ubuntu-bootstrap.sh
  SHELL
end
