#!/bin/bash

# Load options
source ~/.tmux/configs/options.conf

# Load custom options
source ~/.tmux/custom_options.conf

# Load bindings
source ~/.tmux/configs/binds.conf

# Load theme
source ~/.tmux/configs/theme.conf

run 'sh ~/.tmux/scripts/scripts.sh _apply_configuration'

run 'sh ~/.tmux/scripts/override_bindings.sh _override_bindings'

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Status bar stats
set -g @plugin 'samoshkin/tmux-plugin-sysstat'
set -g @sysstat_mem_color_low "grey"
set -g @sysstat_cpu_color_low "grey"

# Fuzzy search
set -g @plugin 'sainnhe/tmux-fzf'

# Better mouse
# set -g @plugin 'nhdaly/tmux-better-mouse-mode'
# set -g @scroll-down-exit-copy-mode "off"
# set -g @scroll-without-changing-pane "off"
# set -g @emulate-scroll-for-no-mouse-alternate-buffer "off"

# Initialize TPM (keep this line at the very bottom of your tmux.conf).
run -b '~/.tmux/plugins/tpm/tpm'

run 'export DISABLE_AUTO_TITLE=true; ls -1 ~/.tmux/sessions | xargs -I % tmuxp load -d ~/.tmux/sessions/%'
