version: '3'

vars:
  IMAGE_NAME: nix-ubuntu24
  CONTAINER_NAME: nix-sandbox
  CONFIG_DIR: '/{{.HOME}}/.dotfiles'

common: &common_settings
  dir: '/{{ .TASKFILE_DIR }}'
  env:
    DOTFILES_DIR: '{{.CONFIG_DIR}}'

tasks:
  up:
    <<: *common_settings
    cmds:
      - docker compose up --build --no-recreate -d
      - docker compose exec -ti docker-ubuntu-sandbox bash

  install:
    <<: *common_settings
    cmds:
      - docker compose exec -ti docker-ubuntu-sandbox /home/sandbox/.dotfiles/setup/bootstrap/install.sh

  exec:
    <<: *common_settings
    cmds:
      - docker compose exec -ti docker-ubuntu-sandbox bash

  update:
    <<: *common_settings
    cmds:
      - docker compose exec -ti docker-ubuntu-sandbox bash -ic nhhna

  down:
    <<: *common_settings
    cmds:
      - docker compose down

  clean:
    <<: *common_settings
    cmds:
      - docker compose down -v
      - docker compose rm -v
